steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['-v']
  logsBucket: 'gs://logs-bucket-wowhealth'
  serviceAccount: 'projects/wowhealth-nodejs/serviceAccounts/wowhealth-nodejs@appspot.gserviceaccount.com'
  # options:
  logging: GCS_ONLY

- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/Arehman52/wowhealth-cf-be.git']

- name: 'node'
  entrypoint: 'npm'
  args: ['-v']

- name: 'node'
  entrypoint: 'npm'
  args: ['install']
  # logsBucket: 'gs://logs-bucket-wowhealth'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - gcloud
  - functions
  - deploy
  - wowhealth-nodejs-function
  - --region=us-central1
  - --allow-unauthenticated
  - --entry-point=index.js
  - --source=.
  - --trigger-http 
  - --runtime=nodejs16




#     - -c
#     - |
#         # Cloud Build doesn't recover the .git file. Thus checkout the repo for this
#         git clone --branch master https://github.com/Arehman52/wowhealth-cf-be.git /tmp/repo ;
#         # Copy only the .git file
#         mv /tmp/repo/.git .





# - name: 'gcr.io/cloud-builders/git'
#  args: ['pull','origin','master']

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install']

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['run','build']

  # logsBucket: 'gs://_Default'
  # build:
  #   logsBucket:

  


# steps:

# - name: 'gcr.io/cloud-builders/git'
#  args: 
#  - init



# steps:
# - name: 'gcr.io/cloud-builders/git'
#   entrypoint: /bin/bash
#   args: ['init']





# - name: 'gcr.io/cloud-builders/npm'
#   description: | 
#   - sdsadasdsadadasdadasdasdasd
#   args: ['install']
