steps:

- name: 'gcr.io/cloud-builders/git'
 args: 
 - init



# steps:
# - name: 'gcr.io/cloud-builders/git'
#   entrypoint: /bin/bash
#   args:
#     - -c
#     - |
#         # Cloud Build doesn't recover the .git file. Thus checkout the repo for this
#         git clone --branch master https://github.com/Arehman52/wowhealth-cf-be.git /tmp/repo ;
#         # Copy only the .git file
#         mv /tmp/repo/.git .





# - name: 'gcr.io/cloud-builders/git'
#  args: ['pull','origin','master']

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install']

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['run','build']

  # logsBucket: 'gs://_Default'
  # build:
  #   logsBucket: 'gs://_Default'

- name: 'gcr.io/cloud-builders/gcloud'
  # options:
  # build:
  #   logging: CLOUD_LOGGING_ONLY
  args:
  - gcloud
  - functions
  - deploy
  - wowhealth-nodejs-function #functionName
  - --region=us-central1
  - --allow-unauthenticated
  - --entry-point=index.js
  - --source=.
  - --trigger-http
  - --runtime=nodejs16

