steps:

# - name: 'https://console.cloud.google.com/gcr/images/cloud-builders/GLOBAL/git'
#  args: ['clone', 'https://github.com/Arehman52/wowhealth-cf-be']

# - name: 'gcr.io/cloud-builders/git'
#  args: ['pull','origin','master']

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install']

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['run','build']

- name: 'gcr.io/cloud-builders/gcloud'
  logsBucket: 'gs://_Default'
  options:
    logging: CLOUD_LOGGING_ONLY 
  args:
  - gcloud
  - functions
  - deploy
  - wowhealth-nodejs-function #functionName
  - --region=us-central1
  - --allow-unauthenticated
  - --entry-point=index.js
  - --source=.
  - --trigger-http
  - --runtime=nodejs16

