steps:
- name: 'gcr.io/cloud-builders/git'
 args: ['pull','origin','master']

- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run','build']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - wowhealth-nodejs-function #functionName
  - --region=us-central1
  - --allow-unauthenticated
  - --entry-point=index.js
  - --source=.
  - --trigger-http
  - --runtime=nodejs16